### ISSUE TITLE
[NOTICE] Failed To Fetch OpenBenchmarking.org Repository Data: pts, and system

### ISSUE THREAD

**Issue by kamal2222ahmed** [phoronix-test-suite/phoronix-test-suite#239]
[root@ip-10-103-137-85 phoronix-test-suite]# /usr/bin/phoronix-test-suite

[NOTICE] Failed To Fetch OpenBenchmarking.org Repository Data: pts

[NOTICE] Failed To Fetch OpenBenchmarking.org Repository Data: system

Phoronix Test Suite v7.8.0m2 (Folldal)

The **Phoronix Test Suite** is the most comprehensive testing and benchmarking platform available for Linux, Solaris, OS X, and BSD operating systems. The Phoronix Test Suite allows for carrying out tests in a fully automated manner from test installation to execution and reporting. All tests are meant to be easily reproducible, easy-to-use, and support fully automated execution. The Phoronix Test Suite is open-source under the GNU GPLv3 license and is developed by Phoronix Media in cooperation with partners.

View the included PDF / HTML documentation or visit http://www.phoronix-test-suite.com/ for full details.

TEST INSTALLATION

    force-install         [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    install               [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    install-dependencies  [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    make-download-cache
    remove-installed-test [Test]

TESTING

    auto-compare
    benchmark          [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    estimate-run-time  [Test | Suite | OpenBenchmarking ID | Test Result]
    finish-run         [Test Result]
    run                [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    run-random-tests
    run-tests-in-suite
    stress-run         [Test | Suite | OpenBenchmarking ID | Test Result]  ...

BATCH TESTING

    batch-benchmark   [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    batch-install     [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    batch-run         [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    batch-setup
    default-benchmark [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    default-run       [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    internal-run      [Test | Suite | OpenBenchmarking ID | Test Result]  ...

OPENBENCHMARKING.ORG

    clone-result                  [OpenBenchmarking ID]  ...
    list-recommended-tests
    make-openbenchmarking-cache
    openbenchmarking-changes
    openbenchmarking-launcher
    openbenchmarking-login
    openbenchmarking-refresh
    openbenchmarking-repositories
    upload-result                 [Test Result]
    upload-test-profile
    upload-test-suite

SYSTEM

    diagnostics
    interactive
    php-conf
    system-info
    system-sensors

INFORMATION

    info                          [Test | Suite | OpenBenchmarking ID | Test Result]
    list-available-suites
    list-available-tests
    list-available-virtual-suites
    list-installed-dependencies
    list-installed-suites
    list-installed-tests
    list-missing-dependencies
    list-not-installed-tests
    list-possible-dependencies
    list-saved-results
    list-test-usage
    list-unsupported-tests
    search

ASSET CREATION

    build-suite
    debug-benchmark           [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    debug-install             [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    debug-result-parser       [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    debug-test-download-links [Test | Suite | OpenBenchmarking ID | Test Result]
    download-test-files       [Test | Suite | OpenBenchmarking ID | Test Result]  ...
    result-file-to-suite      [Test Result]
    validate-result-file
    validate-test-profile
    validate-test-suite

RESULT MANAGEMENT

    analyze-all-runs                 [Test Result]
    auto-sort-result-file            [Test Result]
    edit-result-file                 [Test Result]
    extract-from-result-file         [Test Result]
    merge-results                    [Test Result]  ...
    refresh-graphs                   [Test Result]
    remove-from-result-file          [Test Result]
    remove-result                    [Test Result]
    rename-identifier-in-result-file [Test Result]
    rename-result-file               [Test Result]
    reorder-result-file              [Test Result]
    result-file-to-csv               [Test Result]
    result-file-to-json              [Test Result]
    result-file-to-pdf               [Test Result]
    result-file-to-text              [Test Result]
    show-result                      [Test Result]
    winners-and-losers               [Test Result]

OTHER

    debug-dependency-handler
    debug-render-test
    debug-self-test
    help
    version

MODULES

    auto-load-module
    list-modules
    module-info      [Phoronix Test Suite Module]
    module-setup     [Phoronix Test Suite Module]
    test-module      [Phoronix Test Suite Module]
    unload-module

USER CONFIGURATION

    enterprise-setup
    network-info
    network-setup
    user-config-reset
    user-config-set

WEB / GUI SUPPORT

    gui
    start-remote-gui-server
    start-ws-server

PHOROMATIC

    start-phoromatic-server

Not sure what is the impact of not being able to Fetch OpenBenchmarking.org Repository Data. I am behind a proxy, but i have exported my proxy environment variables
export http_proxy=http://my proxy:80
export https_proxy=http://my proxy:80

**Comment by michaellarabel** [comment]
Without being able to fetch the OpenBenchmarking.org repository data, you won't be able to install any tests/suites (unless you manually download the data or take other steps).

PTS does respect the http_proxy env var. What is the output of `phoronix-test-suite network-info` ?

**Comment by outkasst** [comment]
I am seeing the same issue in Linux ubuntu machine.. Just installed it from Github (Downloaded and ran install.sh as superuser)..

What was the fix for this "Failed To Fetch OpenBenchmarking.org Repository Data: pts" issue? 
thx

**Comment by michaellarabel** [comment]
@outkasst are you behind a proxy or anything like that? Can you `ping openbenchmarking.org` from the machine?

**Comment by outkasst** [comment]
![image](https://user-images.githubusercontent.com/26562595/36269729-24ddeea4-1237-11e8-852e-189623e494be.png)

**Comment by outkasst** [comment]
I am not a networking expert.. but ping doesnt return anything back..thx

**Comment by michaellarabel** [comment]
This issue is due to something in your network configuration not allowing access to OpenBenchmarking.org, but without knowing if you are using a proxy or have other network restrictions or what, it's difficult to say what the issue would be or how PTS could work around it.

**Comment by outkasst** [comment]
Thanks, Is there a specific port that needs to be opened up? 

thx

**Comment by michaellarabel** [comment]
Just your standard HTTPS ports (80 / 443)

**Comment by outkasst** [comment]
Hi Michael,
So how do I get it working if I am behind a proxy? Looks like I am.  Can you please send an example setup I need to do to get Phoronix working behind  a proxy?

Appreciate your help..

**Comment by michaellarabel** [comment]
Have you tried with the http_proxy environment variable? E.g. documentation at https://wiki.archlinux.org/index.php/proxy_settings

**Comment by outkasst** [comment]
Hi Michael,
I did the proxy settings..  as below.. but the port numbers are different, as required by my network. Could this cause issues? I believe 80/443 needs to be somehow be there?
example of what I did:
export http_proxy=http://my proxy:922
export https_proxy=http://my proxy:922

**Comment by michaellarabel** [comment]
I will have to do some checking, I think I have PTS correctly  working when HTTP/HTTPS proxies are on different ports, as previously worked it in there for others but basically rely upon user testing for the proxy features. Will post shortly after checking again.

**Comment by outkasst** [comment]
Hi Michael & All,

I was able to fix the problem by just setting up the proxy using the
"phoronix-test-suite network-setup " , I just put my proxy information during this setup and it is working..

Appreciate your help..

thx

**Comment by michaellarabel** [comment]
Ah great, cheers.

**Comment by jksri** [comment]
> phoronix-test-suite network-setup

hey i had the same issue. when i go through phoronix-test-suite network-setup, its showin me an error that set up is failed.

[root@jf phoronix-test-suite]# phoronix-test-suite network-setup


    [NOTICE] Failed To Fetch OpenBenchmarking.org Repository Data: pts. If this issue persists, contact support@phoronix-test-suite.com.

    [NOTICE] Failed To Fetch OpenBenchmarking.org Repository Data: system. If this issue persists, contact support@phoronix-test-suite.com.

Phoronix Test Suite v8.6.0m0
Network Setup

    Configure the Phoronix Test Suite to use a HTTP proxy (y/N): y

Enter IP address / server name of proxy: ipadress of the server / https://proxy-*******

Enter TCP port for proxy server: port

Enter user-name for proxy (leave blank if irrelevant):

Testing Proxy Server (ipaddress of server / https://proxy:port)

Proxy Setup Failed.

**Comment by michaellarabel** [comment]
@jksri if you try using http:// rather than https:// does it work?

**Comment by jksri** [comment]
Hey it worked when i gave proxy:port
mentioned neither http or https
Thanks

**Comment by michaellarabel** [comment]
Great to hear, thanks. I will look at having it try dropping http/https from the URLs when entered to help other users moving forward.

**Comment by Zerophase** [comment]
Yeah, I do not have a proxy setup and I'm having issues connecting to openbenchmarking.org as well.

**Comment by michaellarabel** [comment]
@Zerophase are you able to connect now?

**Comment by Zerophase** [comment]
Yeah, I can connect without issue now.

**Comment by Young768** [comment]
Hi @michaellarabel  I install Phoronix via sudo apt install on my Ubuntu 16.04. I met the error Failed To Fetch OpenBenchmarking.org. I did try to run network-setup and use both https://proxy- and http://proxy- with and without :port. All of these failed. Do you have any idea to fix it?

**Comment by michaellarabel** [comment]
@Young768 what IP are you trying to connect from? Or actually, try again and I'll flush the firewall blocks again in case it was a false positive block.

**Comment by Young768** [comment]
Hi @michaellarabel. My public IP is 134.134.139.74. The proxy setup still failed. Is there any configuration file that I can configure the network proxy?

**Comment by deanflanders** [comment]
Hello, It seems we also might be blocked from this site, can you please check if you are blocking the IP 195.176.238.195? Or it will be very close to that IP as we use NAT, maybe somehow we got onto the block list. Thanks, Dean

**Comment by michaellarabel** [comment]
@deanflanders - should be fixed now.

**Comment by deanflanders** [comment]
Thanks! And it worked for a bit, then we started to test again, and got blocked again. However, I think we found the issue. Apparently when using wget one needs to define the user-agent setting, info when going via our squid proxy [here](https://askubuntu.com/questions/409998/proxy-blocking-apt-get-allowing-wget-curl). I assume my colleagues have scripts that are not defining the user-agent and failing to connect for some reason, and then maybe keep trying, and then get added to your block list either because of the user-agent setting issue and/or too many attempts. Can you please remove us again? And we will try to get this correct on our end ASAP to prevent this from happening. Our appologies, we made some large changes on our network to require use of the proxy, and this was an unexpected side affect.

**Comment by michaellarabel** [comment]
@deanflanders should be all set now and also put the IP on a permanent greenlist.

**Comment by deanflanders** [comment]
Thanks for unblocking our IP. We can get it to work consistently, however, when going via our proxy using wget https it still fails.
---------------------------------------------------
Command:
wget --server-response https://phoronix-test-suite.com/releases/phoronix-test-suite-9.8.0.tar.gz
---------------------------------------------------
Server-response:
  HTTP/1.1 403 Forbidden
  Date: Sun, 20 Sep 2020 09:24:23 GMT
  Server: Apache
  Content-Length: 318
  Connection: close
  Content-Type: text/html; charset=iso-8859-1
2020-09-20 11:24:24 ERROR 403: Forbidden.
---------------------------------------------------
It seems related to SNI or certificate checks? Can you tell us what the apache error log says is the problem?

Sorry to both you with this, just that we have done a lot of testing and cannot seem to fix/figure it out at our end.

Thanks!

Dean

**Comment by michaellarabel** [comment]
Dean, does it work now? Just tweaked a security setting.

**Comment by deanflanders** [comment]
Wow, great, it works now. What was the setting/issue? We appreciate this as we could not really figure out the issue. Thanks!
