### ISSUE TITLE
Running Phoromatic server-local tests on clients

### ISSUE THREAD

**Issue by swarth100** [phoronix-test-suite/phoronix-test-suite#255]
Hey Michael,

I've seen you've done a great job at adding the option to write up local test-profiles from within the Phoromatic client. I wanted to ask if you were planning on adding a utility which would zip them up to the openbenchmarking.org directory (updating the index files), so that the tests can be distributed to clients as well.

I currently have a script that does this; it watches the test-profiles/local directory and updates the compressed versions/index-file upon changes, just wanted to know if you were planning on implementing it as part of PTS itself.

Thanks, and, once again, keep up the awesome work!
Alberto

**Comment by michaellarabel** [comment]
The Phoromatic Server with 8.0 Git should already be capable of serving custom (local/) tests to PTS clients. Are you experiencing otherwise? (There are a few corner cases where it might not be served currently, but am looking to have them resolved over the next week or so; if you can clarify your deployment path / behavior, can verify. Thanks)

**Comment by swarth100** [comment]
Thank you for your prompt reply!

My final aim was to able to select local tests from within the "build-suite" utility of phoromatic. So that users will be able to create tests, build suites, and deploy them to the clients without ever touching the CLI.
A workaround to deploying to openbenchmarking.org (for quick local testing), was to write up the test under the test-profiles/local, and then zip up the contents to the openbenchmarking.org/local directory, unpating the index accordingly.

I might be wrong (double testing this), yet if I don't perform this step, the local test will not show from within the Build Suite menu.

The same process seems to be applying when tests are created using the newly introduced "Create New Test Profile"

**Comment by michaellarabel** [comment]
This issue should be fixed in Git now for ensuring local tests appear in all appropriate locations, etc.

With regards to test propagation from the Phoromatic Server from the server to client, there are no known issues. If your client system is aware of the Phoromatic Server either from being registered via phoromatic.connect, adding the IP:PORT to the <PhoromaticServers> in the user-config file, or from auto-discovery via Avahi, if a given test isn't found on the local client system, it will query the Phoromatic Server(s) looking for a match. Just checked again in a few combinations and that is working fine.

Let me know if any other issues persist, thanks.

**Comment by swarth100** [comment]
Hello Michael, thanks for fixing the missing tests from the Create Test Suite options, local tests seem to now be displaying correctly.

I was just working on the tips you gave me, and I seem to still have a bunch of issues.

The test-profile I have been testing with is the same as described in #257.

- - - 
When I run the test locally to the phoromatic server I get the following:

- - - 
Now this is how one of the clients is configured (the `user-config.xml`):
```
<?xml version="1.0"?>
<!--Phoronix Test Suite v8.0.0m3-->
<?xml-stylesheet type="text/xsl" href="xsl/pts-user-config-viewer.xsl"?>
<PhoronixTestSuite>
  <Options>
    <OpenBenchmarking>
      <AnonymousUsageReporting>FALSE</AnonymousUsageReporting>
      <IndexCacheTTL>3</IndexCacheTTL>
      <AlwaysUploadSystemLogs>FALSE</AlwaysUploadSystemLogs>
    </OpenBenchmarking>
    <General>
      <DefaultBrowser></DefaultBrowser>
      <UsePhodeviCache>TRUE</UsePhodeviCache>
      <DefaultDisplayMode>DEFAULT</DefaultDisplayMode>
      <PhoromaticServers>phoronix:8888</PhoromaticServers>
      <FullOutput>TRUE</FullOutput>
      <ColoredConsole>AUTO</ColoredConsole>
    </General>
    <Modules>
      <LoadModules>toggle_screensaver, update_checker, perf_tips, ob_auto_compare</LoadModules>
    </Modules>
    <Installation>
      <RemoveDownloadFiles>FALSE</RemoveDownloadFiles>
      <SearchMediaForCache>TRUE</SearchMediaForCache>
      <SymLinkFilesFromCache>FALSE</SymLinkFilesFromCache>
      <PromptForDownloadMirror>FALSE</PromptForDownloadMirror>
      <EnvironmentDirectory>~/.phoronix-test-suite/installed-tests/</EnvironmentDirectory>
      <CacheDirectory>~/.phoronix-test-suite/download-cache/</CacheDirectory>
    </Installation>
    <Testing>
      <SaveSystemLogs>TRUE</SaveSystemLogs>
      <SaveInstallationLogs>FALSE</SaveInstallationLogs>
      <SaveTestLogs>FALSE</SaveTestLogs>
      <RemoveTestInstallOnCompletion></RemoveTestInstallOnCompletion>
      <ResultsDirectory>~/.phoronix-test-suite/test-results/</ResultsDirectory>
      <AlwaysUploadResultsToOpenBenchmarking>FALSE</AlwaysUploadResultsToOpenBenchmarking>
      <AutoSortRunQueue>TRUE</AutoSortRunQueue>
    </Testing>
    <TestResultValidation>
      <DynamicRunCount>TRUE</DynamicRunCount>
      <LimitDynamicToTestLength>20</LimitDynamicToTestLength>
      <StandardDeviationThreshold>3.50</StandardDeviationThreshold>
      <ExportResultsTo></ExportResultsTo>
      <MinimalTestTime>2</MinimalTestTime>
    </TestResultValidation>
    <BatchMode>
      <SaveResults>TRUE</SaveResults>
      <OpenBrowser>FALSE</OpenBrowser>
      <UploadResults>TRUE</UploadResults>
      <PromptForTestIdentifier>TRUE</PromptForTestIdentifier>
      <PromptForTestDescription>TRUE</PromptForTestDescription>
      <PromptSaveName>TRUE</PromptSaveName>
      <RunAllTestCombinations>TRUE</RunAllTestCombinations>
      <Configured>FALSE</Configured>
    </BatchMode>
    <Networking>
      <NoInternetCommunication>FALSE</NoInternetCommunication>
      <NoNetworkCommunication>FALSE</NoNetworkCommunication>
      <Timeout>20</Timeout>
      <ProxyAddress></ProxyAddress>
      <ProxyPort></ProxyPort>
      <ProxyUser></ProxyUser>
      <ProxyPassword></ProxyPassword>
    </Networking>
    <Server>
      <RemoteAccessPort>RANDOM</RemoteAccessPort>
      <Password></Password>
      <WebSocketPort>RANDOM</WebSocketPort>
      <AdvertiseServiceZeroConf>TRUE</AdvertiseServiceZeroConf>
      <AdvertiseServiceOpenBenchmarkRelay>TRUE</AdvertiseServiceOpenBenchmarkRelay>
      <PhoromaticStorage>~/.phoronix-test-suite/phoromatic/</PhoromaticStorage>
    </Server>
  </Options>
</PhoronixTestSuite>
```
From Phoromatic I created a simple Test Suite containing only the local/test-1.0.0 mentioned above. I deployed this test to the client.

I, though, get the following results:
```
$ phoronix-test-suite phoromatic.explore

NOTICE: The following PHP extensions are OPTIONAL but recommended:

GD        The GD library is recommended for improved graph rendering.
Bzip2     The bzcompress/bzip2 support can be used for greater file compression.
CURL      CURL is recommended for an enhanced download experience.



Phoronix Test Suite v8.0.0m4
Phoromatic Servers


IP: phoronix
HTTP PORT: 8888
WEBSOCKET PORT: 8880
SERVER: PHP 7.2.5-0ubuntu0.18.04.1 Development Server
PHORONIX TEST SUITE: Phoronix Test Suite v8.0.0m4 [7940]
DOWNLOAD CACHE: 
SUPPORTED OPENBENCHMARKING.ORG REPOSITORIES:
      local - Last Generated: 11 May 2018 15:16
      pts - Last Generated: 29 May 2018 09:18
      system - Last Generated: 29 May 2018 09:18
```

```
$ phoronix-test-suite phoromatic.connect


[PROBLEM] No Tests Found For Installation. 

[PROBLEM] You must enter at least one test, suite, or result identifier to run.
```

```
$ phoronix-test-suite phoromatic.connect phoronix:8888/NCFKTM


Phoronix Test Suite v8.0.0m4
Server IP: phoronix
Server HTTP Port: 8888
Account ID: NCFKTM


[PROBLEM] No Tests Found For Installation. 

[PROBLEM] You must enter at least one test, suite, or result identifier to run. 
```
- - -

I was wondering if I might have accidentally skipped a step or two in the client-server configuration

**Comment by swarth100** [comment]
@michaellarabel 
Just a heads-up on the issue:

It doesn't seem to run from the CLI as well:

On the **client**:
```
$ phoronix-test-suite phoromatic.explore

Phoronix Test Suite v8.0.0m5
Phoromatic Servers

IP: phoronix
HTTP PORT: 8888
WEBSOCKET PORT: 8880
SERVER: PHP 7.2.5-0ubuntu0.18.04.1 Development Server
PHORONIX TEST SUITE: Phoronix Test Suite v8.0.0m5 [7950]
DOWNLOAD CACHE: 
SUPPORTED OPENBENCHMARKING.ORG REPOSITORIES:
      local - Last Generated: 01 Jan 1970 01:00
      pts - Last Generated: 01 Jun 2018 13:33
      system - Last Generated: 01 Jun 2018 13:33

(base) gresearch@power9.ilab.local ➜   .phoronix-test-suite  phoronix-test-suite run local/deploy-test-1.0.0                          

[PROBLEM] Invalid Argument: local/deploy-test-1.0.0 

CORRECT SYNTAX:
phoronix-test-suite run [Test | Suite | OpenBenchmarking ID | Test Result]  ...

Recently Saved Test Results:
[...]
```

And on the **server**:
```
$ phoronix-test-suite run local/deploy-test-1.0.0

[PROBLEM] local/deploy-test-1.0.0 is not installed. 
    Would you like to stop and install these tests now (Y/n): y

Phoronix Test Suite v8.0.0m5

    To Install:    local/deploy-test-1.0.0

[NOTICE] Trying to get property 'Downloads' of non-object in pts_test_profile:456
    Determining File Requirements ................................................................................................
    Searching Download Caches ....................................................................................................

    1 Test To Install

    local/deploy-test-1.0.0:
        Test Installation 1 of 1

[...]
```

**Comment by swarth100** [comment]
Both `install` and `run` commands fail with the following output:

```
$ phoronix-test-suite install local/deploy-test-1.0.0 

[PROBLEM] Invalid Argument: local/deploy-test-1.0.0

CORRECT SYNTAX:
phoronix-test-suite install [Test | Suite | OpenBenchmarking ID | Test Result]  ...

Recently Saved Test Results:
[...]
```

- - -
File structure on the server:
```
$ tree -P "deploy-test*" --matchdirs --prune
.
`-- var
    `-- lib
        `-- phoronix-test-suite
            |-- installed-tests
            |   `-- local
            |       `-- deploy-test-1.0.0
            |           `-- deploy-test
            `-- test-profiles
                `-- local
                    `-- deploy-test-1.0.0
```

The `user-config.xml` on all three clients I am using to test is the one above.

**Comment by swarth100** [comment]
@michaellarabel 
Sorry to disturb you once again,
was just wondering if there's anything else you would suggest trying to attempt to fix this issue.

Should the issue persist I should have some spare time in a few weeks to properly step through the code attempting to debug the issue. A heads-up on what module handles this explcitly?

I was personally having a look inside the [https://github.com/phoronix-test-suite/phoronix-test-suite/blob/5e80315a2583a22e441436131c519e32478feb93/pts-core/objects/client/pts_test_install_request.php#L176](pts_test_install_request.php) file, in particular the logic of the `scan_download_caches` method.
