### ISSUE TITLE
Several tests failing on FreeBSD 10.1

### ISSUE THREAD

**Issue by cen1** [phoronix-test-suite/phoronix-test-suite#59]
Botan, blake2, 7zip, OpenSSL, Simple Pi all fail on FreeBSD 10.1 I have logs from the first three. From this "statistical evidence" I believe there might be more of them. Might be a good idea to re-run all tests and see what else fails.

```
The following tests failed to install:

  - pts/blake2-1.1.0
  - pts/compress-7zip-1.6.0
pts/botan-1.1.0        : Test: AES-256
pts/botan-1.1.0        : Started Run 1 @ 23:11:12
pts/botan-1.1.0        : Average: 0 Mbytes/spts/compress-7zip-1.6.0: Test Starting
pts/compress-7zip-1.6.0: Started Run 1 @ 23:11:18
pts/compress-7zip-1.6.0: Started Run 2 @ 23:11:20
pts/compress-7zip-1.6.0: Started Run 3 @ 23:11:22
pts/compress-7zip-1.6.0: Average: 0 MIPS

The following tests failed to properly run:

        - pts/botan-1.1.0: Test: AES-256
        - pts/compress-7zip-1.6.0: Compress Speed Test

    Installed: pts/botan-1.1.0
    To Install: pts/blake2-1.1.0
    To Install: pts/compress-7zip-1.6.0

    Determining File Requirements ..........................................
    Searching Download Caches ..............................................

    2 Tests To Install
        1 File To Download [0.44MB]
        12MB Of Disk Space Is Needed

    pts/blake2-1.1.0:
        Test Installation 1 of 2
        1 File Needed [0.44 MB / 1 Minute]
        Downloading: blake2_code_20130131.zip                       [0.44MB]
            Download Failed: https://blake2.net/blake2_code_20130131.zip
            Downloading of needed test files failed.
    pts/compress-7zip-1.6.0:
        Test Installation 2 of 2
        1 File Needed [3.66 MB / 1 Minute]
        File Found: p7zip_9.20.1_src_all.tar.bz2                    [3.66MB]
        Installation Size: 10 MB
        Installing Test @ 23:12:17
            The installer exited with a non-zero exit status.
            ERROR: Missing Command: ++
            LOG: ~/.phoronix-test-suite/installed-tests/pts/compress-7zip-1.6.0/install-failed.log
```

install-failed.log
7zip wants g++ for some reason while default compiler is clang

```
--- common ---
mkdir -p bin
--- 7za ---
make -C CPP/7zip/Bundles/Alone all
--- myGetTickCount.o ---
--- wine_date_and_time.o ---
--- myGetTickCount.o ---
g++ -O -pipe -s  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE  -DNDEBUG -D_REENTRANT -DENV_UNIX  -D_7ZIP_LARGE_PAGES  -DBREAK_HANDLER  -DUNICODE -D_UNICODE -c -I.  -I../../../myWindows  -I../../../  -I../../../include_windows ../../../myWindows/myGetTickCount.cpp
g++: not found
*** [myGetTickCount.o] Error code 127

make[1]: stopped in /usr/home/freebsd/.phoronix-test-suite/installed-tests/pts/compress-7zip-1.6.0/p7zip_9.20.1/CPP/7zip/Bundles/Alone
--- wine_date_and_time.o ---
g++ -O -pipe -s  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE  -DNDEBUG -D_REENTRANT -DENV_UNIX  -D_7ZIP_LARGE_PAGES  -DBREAK_HANDLER  -DUNICODE -D_UNICODE -c -I.  -I../../../myWindows  -I../../../  -I../../../include_windows ../../../myWindows/wine_date_and_time.cpp
g++: not found
*** [wine_date_and_time.o] Error code 127

make[1]: stopped in /usr/home/freebsd/.phoronix-test-suite/installed-tests/pts/compress-7zip-1.6.0/p7zip_9.20.1/CPP/7zip/Bundles/Alone
2 errors

make[1]: stopped in /usr/home/freebsd/.phoronix-test-suite/installed-tests/pts/compress-7zip-1.6.0/p7zip_9.20.1/CPP/7zip/Bundles/Alone
*** [7za] Error code 2

make: stopped in /usr/home/freebsd/.phoronix-test-suite/installed-tests/pts/compress-7zip-1.6.0/p7zip_9.20.1
1 error

make: stopped in /usr/home/freebsd/.phoronix-test-suite/installed-tests/pts/compress-7zip-1.6.0/p7zip_9.20.1
```

**Comment by cen1** [comment]
After trying to run even more tests on FreeBSD, it seems that like 80% of benchmarks either fail to install or fail to run properly, usually ending up in infinite loop of fails (benchmark ticket needs to be removed and pts restarted on the client machine). I will try to fix some of these myself but it seems like a major problem across the board.

**Comment by michaellarabel** [comment]
Are you running them through Phoromatic? If so, it's understandable, as from the Phoromatic UI it doesn't show all BSD compatible ones, etc. But rather shows all test profiles, many of which aren't compatible on BSD. With mostly being designed for Linux testing, there isn't an option right now on Phoromatic for showing just BSD (or just Solaris) compatible tests but lists everything, so maybe adding that option is needed. However, if from your BSD system you run "phoronix-test-suite list-tests" it should show only the tests that are supposed to work on BSD.

For many of the other tests, there would need to be patches upstream to the respective programs for improving the BSD support. Or if there's any issues with any of the test profile scripts causing a lack of BSD compatibility, patches are happily accepted there too.

**Comment by cen1** [comment]
I am referring specifically to BSD compatible tests here. Basically, I went through the profiles on http://openbenchmarking.org/tests/pts and specifically picked those which had a BSD icon in the description. 
A subset of them are failing to compile due to lack of gcc but that is only a couple of them. I guess that could easily be solved by an #ifdef in the makefiles but since pts pulls the code directly from upstream that is probably not an option. Then again, you can simply install gcc on BSD and be done with it but it kind of defeats the purpose of "php5-cli is the only dependency" which is nice.

Then there are some of them which compile but the tests return zero, like botan and 7zip in the above log. I will investigate those further to find the reason behind it.

Was it ever considered to not use upstream packages but host them through openbenchmarking? This way each package could be tweaked a bit and make sure it works on every supported platform, not break and not produce dead mirror links.

**Comment by michaellarabel** [comment]
Unfortunately for as many tests that are there, hosting all of them would not be an option at this point due to having bandwidth caps.

The focus has always been on testing vanilla/upstream packages so that it's easily reproducible by third-parties whether or not they're using PTS. It's the same reason why the default behavior isn't to use whatever packages of tests are provided by a distribution's package repository, since there's potentially unknown patches or odd compiler flags that would make them uncomparable when comparing cross-OS/distributions.

Dead mirror links are corrected when reported.

Some tests do include patches applied against an upstream package, and I'm not opposed to doing that with a test profile patching an upstream source package, when it just comes down to fixing the build environment or similar things.

**Comment by cen1** [comment]
I guess with patches you mean custom install scripts (install.sh)? I think it could be doable with some bash-fu.
How could I test custum profiles? I registered on openbenchmarking but it seems that uploading of custom profiles is disabled.

**Comment by michaellarabel** [comment]
Via the install.sh file, you can either include a small patch (otherwise just download a .patch file separately by adding it to the downloads.xml) and then from within that install script you could use the patch command to patch whatever upstream source program is being tested to better the BSD support. I'm fine with incorporating such patches assuming it just relates to the program's BSD support, etc.

When making any changes to the install.sh file of a test locally, simply re-run phoronix-test-suite benchmark <whatever test> and it will sense that install.sh has been modified (different file hash) and then proceed to re-install the test using the new install.sh file. That's the easiest way to go about testing the work.

Uploading of test profiles is done through the client with phoronix-test-suite upload-test-profile.

**Comment by cen1** [comment]
So far I was able to solve some of the problematic tests by simply installing gcc and bash on FreeBSD. Botan also needs python but still fails to compile due to additional flags needed for gcc on FreeBSD. Plus a fact that g++ never exists on FreeBSD because they append a version on the end of it (g++48).

I feel like some universal checks would be needed before running install.sh to make sure that all the tools needed to run the script are installed, not just blindly run it and fail. Perhaps list the basic dependencies in some xml so you know you have to install them before even trying to run the test. Or perhaps just a big ifdef wrapper to completely separate installation process for each platform so it can complete as natively as possible.

**Comment by michaellarabel** [comment]
PTS does have its "external dependencies" concept for specifying dependencies needed by a test that it will attempt to install prior to installing the test. See the pts-core/external-dependencies/ for more details. However, it doesn't check for 100% of possible deps but just the most common ones and largely assumes you at least have bash and other basic support available.

PTS does also support postfixing the install.sh so if you were to create install_bsd.sh it would only run on BSDs.

**Comment by cen1** [comment]
Sounds good. Most of the tests can probably be fixed with a few more ExternalDependencies listed. I will come back to this issue when I manage to fix a few of them.

**Comment by michaellarabel** [comment]
Hi @cen1 just checking back to see if you were able to fix any of them with added external dependencies?

**Comment by michaellarabel** [comment]
The test profiles in this thread have all seen updates since this thread/report was created, just doing some maintenance of these tickets now. As far as I am aware all of these tests are working fine on latest FreeBSD with PTS.
